# Generated by Django 4.1.7 on 2023-06-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(default="Not Disclosed", max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="illness_history",
            field=models.TextField(default=""),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
