# Generated by Django 4.1.7 on 2023-06-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_age_user_gender_user_illness_history_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="prescriptions",
            field=models.TextField(default=""),
        ),
    ]
