# Generated by Django 4.1.7 on 2023-06-08 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_doctor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(default="")),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("ENT", "ENT"),
                            ("Cardiologist", "Cardiologist"),
                            ("Neurologist", "Neurologist"),
                            ("Oncologist", "Oncologist"),
                            ("Orthopedia", "Orthopedia"),
                            ("Pediatrician", "Pediatrician"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
