# Generated by Django 4.1.7 on 2023-06-08 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_billing_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billing",
            name="description",
        ),
    ]
