# Generated by Django 4.1.7 on 2023-06-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_billing_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="approval",
            field=models.BooleanField(default=False),
        ),
    ]
