# Generated by Django 4.1.7 on 2023-06-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_approved_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="complaints",
            field=models.TextField(default=""),
        ),
    ]
