# Generated by Django 4.1.7 on 2023-06-05 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_user_alter_profile_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
