# Generated by Django 4.1.7 on 2023-06-06 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_delete_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
